services:
  nextapp:
    build: .
    container_name: nextapp
    ports:
      - 4173:4173
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./.env
  
  nginx:
    restart: always
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - nextapp
