services:
  nextapp:
    build: .
    ports:
      - "4173:4173"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextapp
