services:
  nextapp:
    build: .
    container_name: nextapp
    ports:
      - "4173:4173"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
  
  nginx:
    restart: always
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - nextapp
